name = "open-mool-api"
compatibility_date = "2024-01-01"
main = "src/index.ts"

[vars]
# Environment variables

[[d1_databases]]
binding = "DB"
database_name = "open-mool-db"
database_id = "open-mool-db-id"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "open-mool-storage"

# [ai]
# binding = "AI"
